// error codes auth
export const USERNAME_IS_ALREADY_IN_USE = '@auth/USERNAME_IS_ALREADY_IN_USE';
export const INCORRECT_USERNAME = '@auth/INCORRECT_USERNAME';
export const INCORRECT_PASSWORD = '@auth/INCORRECT_PASSWORD';
export const INVALID_OR_EXPIRED_TOKEN = "@auth/INVALID_OR_EXPIRED_TOKEN"