export { default as register } from './register'
export { default as login } from './login'
export { default as get } from './get'
export { default as create } from './create'
export { default as getById } from './getById'
export { default as delete } from './delete'